### ISSUE TITLE
Additional leading slashes between hostname and IIIF resources

### ISSUE THREAD

**Issue by anarchivist** [minicomp/wax_tasks#10]
**Describe the bug**
There are are additional slashes between the hostname and the path for IIIF resources in manifests, etc.

**To Reproduce**
1. Check out the repo (a minimal wax exhibition): https://github.com/anarchivist/chandlery.git
2. Build using the following:
```
bundle exec rake wax:derivatives:iiif
bundle exec rake wax:pagemaster
bundle exec jekyll build
```
3. Inspect the output

**Expected behavior**
Something like`https://example.com/img/derivatives/iiif/MKP_392_0032/manifest.json` should appear instead of  `https://example.com//img/derivatives/iiif/MKP_392_0032/manifest.json`

**Comment by mnyrop** [comment]
@anarchivist  Yep this is a bug. This is what it's doing right now:

`"@id": "{{ '' | absolute_url }}/img/derivatives/iiif/MaryKalhorPhotography_392_0032/manifest.json",`

... which is what makes it work on `localhost` and `prod` while creating the absolute URI iiif requires.
It looks like the double slash happens when there's no site `baseurl`.

I'll play around to find a better solution. In the meantime, is it still technically working? Or does this break something in your viewer atm?
