### ISSUE TITLE
Is lowercase necessary for PIDs?

### ISSUE THREAD

**Issue by awoods** [minicomp/wax_tasks#49]
In the "Requirements" section of the [Metadata file](https://minicomp.github.io/wiki/wax/preparing-your-collection-data/metadata/) description, it notes that the `pid`:
> should follow “snake case”, where letters are lowercase, special characters are removed, and spaces are replaced by underscores

Is the lowercase requirement actually a requirement? Out PIDs and corresponding image files include uppercase characters. We could rename the files... but that turns a seamless production workflow into a slightly more complicated / error-prone one.

Reference:
https://github.com/minicomp/wax_tasks/blob/39f570dc72df65f9d87133e16353913da6bd3d77/lib/wax_tasks/utils.rb#L111

**Comment by mnyrop** [comment]
@awoods currently, yes. because wax is maybe first and foremost a teaching tool, we wanted to set really clear expectations for the (meta)data upfront to avoid opaque inconsistencies in collection processing / mapping records to asset files. that said, i'm definitely open to your perspective here.

i've considered making a utility script for bulk renaming files according to wax's preconditions (using the same code you quoted above, for consistency.) the script could also spit out a 2 column CSV with (1) original file names and (2) what they were renamed as, in order to make this process more transparent. would something like that be useful? and if not, what renaming processes were you considering as a backup option to this problem? i'd be curious to know, and it might help inform code changes / documentation additions to fit how folks *actually* work.

**Comment by mnyrop** [comment]
(closing the issue because it's not an issue per se, but we can keep chatting + i can reopen it if action items arise.)

**Comment by awoods** [comment]
Thanks for the response, @mnyrop . 

Currently, the Lake County Library's workflow produces image files like: `00001CC.tif`, `00002CC.tif`, etc. I was hoping to mount their images directory underneath Wax's "_data" directory, and generate the derivatives. If the filenames have to be lower-cased, then that means I will likely need to create a workflow for copying the renamed files.

Fundamentally, I am wondering if the removal of `.downcase` in the [referenced code](https://github.com/minicomp/wax_tasks/blob/39f570dc72df65f9d87133e16353913da6bd3d77/lib/wax_tasks/utils.rb#L111) would break other elements of Wax.
